markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6	
paginate_path: page/:num


# Build settings
# markdown: redcarpet
# redcarpet:
#     extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

#SyntaxHihglighter config start

SyntaxHihglighter: false
shTheme: shThemeDefault # shThemeDefault  shThemeDjango  shThemeEclipse  shThemeEmacs  shThemeFadeToGrey  shThemeMidnight  shThemeRDark

#SyntaxHihglighter config end

blog:
    name: Damian                                                    # 博客名称
    description: Damian is going to the github.                     # 博客描述
    title: Damian Zhou                                              # 网页标题
    url: http://damian.github.io/                                   # 博客地址
    duoshuo: DamianZhou                                             # 多说ID 
    tongji: e0d9a75a7e53b54cd1e6649facd5906e                        # 百度统计ID
    clickiTongJi: 51831					                            # Clicki统计ID
    qiniu:                                                          # 七牛云地址
author:
    name: Damian                                                    # 作者名称
    email: zhoucaidong@gmail.com                                    # 邮箱地址
    weibo: http://weibo.com/zhoucaidong                             # 微博地址
    github: https://github.com/DamianZhou                           # GitHub地址
    logo: /res/img/icon.jpg                                         # logo地址
    douban:
        name:                                                       # 豆瓣地址名称
        key:                                                        # 豆瓣API Key